### ISSUE TITLE
Not finding all closures/alerts

### ISSUE THREAD

**Issue by bdhhtb** [nagatak/cs294#3]
At the time of writing, the following URL has 3 warnings http://www.nps.gov/havo/closed_areas.htm
- Nov 3: something something nene
- Sep 23: something something falling trees
- May 7: something something steep cliffs

However, I ran the script and only obtained JSON output for the second warning. Should I have gotten all three?

**Comment by nagatak** [comment]
The script only grabs what is in the alert container (see pic below), in this case it is the second warning. 

<img width="639" alt="havoalert" src="https://cloud.githubusercontent.com/assets/13956089/11047517/f8aac93a-86d6-11e5-9dfb-2b30e895ad75.png">

This is done because we have limited space in the notification tags (see pic below).

<img width="381" alt="notificationtab" src="https://cloud.githubusercontent.com/assets/13956089/11047501/df468aba-86d6-11e5-930f-809eebde34ff.png">

So, we are working under the assumption that the NPS will put what they believe to be important in the alert container. As for the current closures we are currently taking the easy way out and providing a link in the app to the webpage. Basically, "for more information on current closures and hazards click here."

**Comment by bdhhtb** [comment]
:+1:
